### ISSUE TITLE
socket auth?

### ISSUE THREAD

**Issue by cognifloyd** [fabianlindfors/sockethook#1]
It looks like any websocket client can subscribe to any stream of webhooks.
Is there a way to require some kind of authentication for websocket clients?
Basic auth, an auth key header, or something else?

**Comment by fabianlindfors** [comment]
There isn't any built-in way currently. It would be a bit hard to implement in a flexible way. The way I would add authentication is to put sockethook behind a reverse proxy, such as nginx, and handle authentication on that level. This grants a lot more flexibility!

I'm also thinking about adding some simple authentication built-in but I'm not sure what that would look like yet!
